### ISSUE TITLE
Reuse Same Model for Subsequent Runs?

### ISSUE THREAD

**Issue by drgrib** [neonbjb/tortoise-tts#130]
I'm trying to create custom voice output off of limited samples and I'm noticing different voices for the same text on subsequent runs. Some of these voices are better matches than others. Is there a way to lock output to use one of the models from previous runs for generation? Or specify the model used with some parameters?

I'm specifically trying to use the

```
python tortoise/do_tts.py
```
and
```
python tortoise/read.py
```

commands and reuse a model obtained in previous runs.

**Comment by neonbjb** [comment]
I can't guarantee it will work, but I'd recommend playing with the `cvvp_amount` command line option to induce stability in the voice. This will come at the cost of less accurate text<->speech alignment. Start with `--cvvp_amount=.5`. The range is [0,1]. `1` is probably a pretty bad idea. :)

Another thing you could try is messing with the [temperature](https://github.com/neonbjb/tortoise-tts/blob/main/tortoise/api.py#L351). This controls how random the output of Tortoise is. Lower temperatures will result in more deterministic (and more boring) outputs. As temperature approaches 0, voices will all start to sound the same and it'll start getting fairly robotic. There is probably a happy medium for your voice, the default is set to something that I personally found to be a good balance. Since this setting is not exposed to the CLI you'll need to hack do_tts.py. Shouldn't be too hard though.

> reuse a model
I think your terminology here is incorrect but I just want to clarify. Unless you've re-trained Tortoise, you're always using the same models. I think you mean "reuse the sound of a previously generated voice"?

**Comment by drgrib** [comment]
Yes. That is what I meant, thank you. I had just a few samples and was getting pretty high variance in output. So I was trying to find a way to get consistent results.

However, it looks like my solution may just be to try to find more samples. I tried a second custom voice for which I had many high quality samples and noticed that all 3 generated wav outputs sound like good matches and are almost exactly the same voice.

**Comment by neonbjb** [comment]
Ah, good to hear! Good data is definitely a better approach than trying to tweak the generation knobs. If nothing else, it'll be more consistent.
