### ISSUE TITLE
Other language support

### ISSUE THREAD

**Issue by ThomasJanssoone** [neonbjb/tortoise-tts#131]
Hello, 

First thank you for all the amazing work

I am looking to use tortoise tts but in French
I tried using another wav2vec extractor with  "jonatasgrosman/wav2vec2-large-xlsr-53-french" but the output is a voice with a lot of distortion at the beginning and a speed-up after

I saw the previous issues about other language generation and I wonder if I should also change the tokenizer.json ?

Thanks in advance for your help
Best

**Comment by neonbjb** [comment]
I think you mean you changed the Wav2Vec2FeatureExtractor in `wav2vec_alignment.py`? That'll just break that module.

To support a new language, you'll need to re-train Tortoise from scratch. I'm guessing the distortion is due to the fact that the model simply doesn't "understand" French. Apologies :(

**Comment by ThomasJanssoone** [comment]
Thank you for the fast answer :) 

I will look into training it in French then

Best

**Comment by raul-parada** [comment]
@ThomasJanssoone could you re-training it into French? I would like to do it to Spanish. Can you tell me the steps did you follow? thanks

**Comment by cristianosoy** [comment]
I am also interested in training a model for Spanish.

**Comment by neonbjb** [comment]
Hey y'all, take a look at past issues or comments.

**Comment by andupotorac** [comment]
@neonbjb it would be helpful if you can add a file that keeps track of the languages the model is actively being trained for, and by whom (so people can cluster more data for specific languages), and make it available here in the repo.

This way the community will eventually get most languages up - ideally with some step-by-step instructions to follow once someone gathers the resources and dataset to train the model.

Otherwise, I think this is the question that will just keep popping up.

**Comment by neonbjb** [comment]
Hey Andu,
Great idea - I would be happy to appoint a moderator to do this, but I do not have time to do it myself.

**Comment by Root-FTW** [comment]
> I am also interested in training a model for Spanish.

lo lograste? :(

**Comment by RaulKite** [comment]
Any advance or guide to train the model in Spanish?

Algún avance o guía para reentrenar el modelo en español?


Thanks

**Comment by myte1why** [comment]
any news about how to train model?

**Comment by Root-FTW** [comment]
> Any advance or guide to train the model in Spanish?
> 
> Algún avance o guía para reentrenar el modelo en español?
> 
> Thanks

misma duda aqui :(
