### ISSUE TITLE
Question about the positional embedding in CLVP

### ISSUE THREAD

**Issue by jry-king** [neonbjb/tortoise-tts#222]
When looking at the model structures of CLVP I found that the size of speech positional embedding is not the length of the input speech sequence but rather the number of speech tokens. Is it on purpose, and if so, could you explain the reason? Thanks!
![image](https://user-images.githubusercontent.com/26543484/208873361-3ec4302d-56e4-4d10-b47a-10deb8871778.png)

**Comment by neonbjb** [comment]
CLVP operates in token space (e.g. it produces a dot product similarity score for a sequence of speech tokens versus a sequence of text tokens). This was done because the primary purpose of CLVP is re-ranking the outputs of the AR model. Producing actual speech from the AR model requires going through the diffusion model, which is very expensive. By being able to directly re-rank AR outputs I save a lot of compute.

**Comment by jry-king** [comment]
I see that CLVP compares the outputs of the AR model (speech tokens) rather than the actual speech against the text tokens, but I think the size of the speech positional embedding should be related to the length of those outputs from the AR model instead of the total number of different speech tokens.
To clarify this with respect to codes, the parameters in the CLVP initialization code looks like this:
![image](https://user-images.githubusercontent.com/26543484/209062162-ed7e0595-d727-4e46-8a39-f1123c5c493a.png)
And I think the code snippet mentioned in the issue can be changed to:
![image](https://user-images.githubusercontent.com/26543484/209062293-491f580e-ddfc-40e3-8ec7-d6b19b989608.png)

**Comment by neonbjb** [comment]
Oh I see, you're right. You can save a substantial amount of parameters in this way but this probably doesn't affect performance. Thanks for pointing this out!
