### ISSUE TITLE
Long text generation

### ISSUE THREAD

**Issue by faad3** [neonbjb/tortoise-tts#24]
Hello, thank you for your excellent work, the results are impressive, I admire you.

When generating long text using a script read.py, the resulting pieces of audio have different characteristics, i.e. the heterogeneity of pronunciation is felt.

Is it possible to somehow achieve a large, homogeneous audio of the entire text?

**Comment by neonbjb** [comment]
Hi there,
In a previous version, I had some code in read.py that I had intended to help with this. It was removed here:
https://github.com/neonbjb/tortoise-tts/commit/5c9377ba341363f5243d49738682816b12e7fed2 - see lines 63-75 in `read.py`.

What this did was it continuously fed previous segments into the reference clips for subsequent segments, such that the reference clips consisted of the actual reference clips you provided *and* clips output by the model.

I removed this because it sometimes caused the program to completely degenerate into unintelligible audio. This wasn't always the case, though. It seemed to happen more often with "unique" voices that were likely far from anything the models were trained on.

You might try reverting those changes to see if it improves your use case.

Another thing you can try to improve consistency is to turn down the `diffusion_temperature`: https://github.com/neonbjb/tortoise-tts/blob/main/tortoise/api.py#L336. This will make the output more bland, but also more predictable.
