### ISSUE TITLE
Unnecessary word insertions

### ISSUE THREAD

**Issue by polariton** [neonbjb/tortoise-tts#40]
Thanks for publishing your work. Very nice results.

I noticed that the model may hallucinate and insert words, if the similar word was already used in the sentence. For example, the sentence "If this is your first night at Fight Club, you have to fight." is pronounced as "If this is your first night at Fight Club, you have to fight **club**." The model is reusing the previously generated expression "Fight Club" instead of pronouncing just one word "fight".

**Comment by neonbjb** [comment]
Hey there, thanks!

Yes, I've noticed this too. It seems to happen more for some voices than others. I don't have a fix right now other than attempting to regenerate the speech a second time.

**Comment by neonbjb** [comment]
It is not autoregressive for text. Every speech token has the full text input as context.

My guess for why this is happening:
The decoding process is guided by a contrastive model called CLVP which encodes both the text and speech into a single vector and computes a similarity score between these two vectors. The representable space within a single vector is fairly constrained, so it probably learns to represent the set of words that are spoken, and not necessarily the order or frequency of those words. 

Such a system might not really care if a single word is spoken more than once. In fact, there may even be cases where the CLVP model predicts a better alignment for incorrectly spoken text because of how it internally represents that text.

As an interesting aside - you can see this in action by trying to get TorToiSe to speak long sentences. They will be of significantly lower quality than shorter ones because you are straining the CLVP model. This is why my `read.py` splits text up into such small snippets.

The initial CLVP model I released with Tortoise was quite small. I believe it is/was the primary bottleneck for produced quality. For this reason, I recently retrained it with a larger representation space and more depth. I released a new version last night with the bigger model, you might try updating and seeing if things have improved.
