### ISSUE TITLE
Find a workaround for high RAM usage maybe?

### ISSUE THREAD

**Issue by exllama-fan** [neonbjb/tortoise-tts#531]
The attempt of speeding up the inference would only make sense if it doesn't keep filling the RAM, only then it would be a production level open source library. What's the point if one has to delete the instance to clear RAM after a few inferences

**Comment by drewbitt** [comment]
Did you consider getting more RAM?

> What's the point 

Probably for people with more RAM

**Comment by exllama-fan** [comment]
wait! I didn't intend to spark a debate around whether it can be run for use case that involves one user or two, I rather meant TTS as a service, where plenty of users are being served real time

**Comment by drewbitt** [comment]
Check out the manuscript in the README, "Better speech synthesis through scaling". The inference pipeline uses large autoregressive transformer, decoding with an attentional diffusion model and vocoding with UnivNet. This is clearly going for performance of the model; it was not a priority to minimize RAM usage so that this can be run as a service, whether commercially or not. 

I'd check out https://github.com/manmay-nakhashi/tortoise-tts-fastest for performance where memory may be slightly improved, or if not, less time is spent per inference allowing for it to better run as a service.

**Comment by exllama-fan** [comment]
The problem is not high ram usage, the problem is ram usage would keep increasing as you keep generating.

**Comment by manmay-nakhashi** [comment]
this issue is fixed on read.py
