### ISSUE TITLE
The sampling algorithm is ddpm or ddim?

### ISSUE THREAD

**Issue by ruaruaruabick** [neonbjb/tortoise-tts#545]
in paper, it's mentioned that the ddim is used when inferencing, but in code the sampler is still DDPM?

**Comment by neonbjb** [comment]
Yeah, I never got around to porting the DDIM inference to this repo (but it does work with very few modifications, and should be able to do inference in very few steps - 16 worked quite well last time I checked).

**Comment by JohnHerry** [comment]
> Yeah, I never got around to porting the DDIM inference to this repo (but it does work with very few modifications, and should be able to do inference in very few steps - 16 worked quite well last time I checked).

Hi, neonbjb, thanks for the good job, I am a green hand and I have some questions to ask.
  I see in the paper that there is a VQVAE  encoder/decoder to convert between  mels and mel codes, then why there need a DDPM to transform the AR generated mel codes into mels ? why not use the VQVAE decoder directly ?
and I see that there are 8192 values for  mel codes,  is that only for TTS usage？ I mean that if we want a generic  mel codec for any kind of voice or sound,  not only speech,  then is the codebook of size 8192 enough?
    I also doubt that why in the paper use DDPM to decode the mel codes into mels, instead of the directly wavform. The paper tell that the training cost on DDPM from mel code to PCM is very expensive,  and the result is not as good as that   DDPM to mel and append a vocoder.  Is that means that DDPM has limitations on decompress signal from low  resolution （mel codes） to high resolution （PCM）？

Thanks

Thanks

**Comment by neonbjb** [comment]
> I see in the paper that there is a VQVAE encoder/decoder to convert between mels and mel codes, then why there need a DDPM to transform the AR generated mel codes into mels ? why not use the VQVAE decoder directly?

The quality of the VQAE decoder was horrendous. The idea behind the DDPM was to improve this. It's possible that you could train a VQGAN to remove the need for the diffusion decoder, but I did not try this for this project.

> and I see that there are 8192 values for mel codes, is that only for TTS usage

The VQAE was trained on speech only so these codes will only really work well for speech. In my experience, increasing the codebook size helps a little bit, but not as much as you might think. If I did it again (and had enterprise hardware) I would have considered larger codebook sizes. On 3090s larger codebook sizes were getting unweildy to train.

> I also doubt that why in the paper use DDPM to decode the mel codes into mels, instead of the directly wavform.

It's likely due to technique. decoding waveform data is challenging. There's been a lot of new research since Tortoise came out that would have helped this work better.

I do still stand by the notion that training cascaded networks sometimes makes more sense than end-to-end ones. There is some undefined relationship between the amount of parameters a model has, the amount of computation applied to a unit of data and the quality of the data generated by a neural network. You really want to apply a lot of compute and parameters to rendering large chunks of audio, not on each individual pressure reading. Finding an architecture that balances that isn't as easy as it might seem at face value.

> Is that means that DDPM has limitations on decompress signal from low resolution （mel codes） to high resolution （PCM)?

This bleeds from the previous answer, but no - it's not a fundamental limitation. If you spent as much compute and parameters on the PCM/waveform data as I do on the MEL codes, you'd get a better result. It'd also be >100x slower than the current model. You have to compromise the model to process ultra-high dimensional data efficiently and this is where it seems to become less advantageous to render directly to PCM/waveform.

**Comment by JohnHerry** [comment]
> > I see in the paper that there is a VQVAE encoder/decoder to convert between mels and mel codes, then why there need a DDPM to transform the AR generated mel codes into mels ? why not use the VQVAE decoder directly?
> 
> The quality of the VQAE decoder was horrendous. The idea behind the DDPM was to improve this. It's possible that you could train a VQGAN to remove the need for the diffusion decoder, but I did not try this for this project.
> 
> > and I see that there are 8192 values for mel codes, is that only for TTS usage
> 
> The VQAE was trained on speech only so these codes will only really work well for speech. In my experience, increasing the codebook size helps a little bit, but not as much as you might think. If I did it again (and had enterprise hardware) I would have considered larger codebook sizes. On 3090s larger codebook sizes were getting unweildy to train.
> 
> > I also doubt that why in the paper use DDPM to decode the mel codes into mels, instead of the directly wavform.
> 
> It's likely due to technique. decoding waveform data is challenging. There's been a lot of new research since Tortoise came out that would have helped this work better.
> 
> I do still stand by the notion that training cascaded networks sometimes makes more sense than end-to-end ones. There is some undefined relationship between the amount of parameters a model has, the amount of computation applied to a unit of data and the quality of the data generated by a neural network. You really want to apply a lot of compute and parameters to rendering large chunks of audio, not on each individual pressure reading. Finding an architecture that balances that isn't as easy as it might seem at face value.
> 
> > Is that means that DDPM has limitations on decompress signal from low resolution （mel codes） to high resolution （PCM)?
> 
> This bleeds from the previous answer, but no - it's not a fundamental limitation. If you spent as much compute and parameters on the PCM/waveform data as I do on the MEL codes, you'd get a better result. It'd also be >100x slower than the current model. You have to compromise the model to process ultra-high dimensional data efficiently and this is where it seems to become less advantageous to render directly to PCM/waveform.

Learned a lot. Thank you for sharing so much precious experience!
