### ISSUE TITLE
why the input samples of VQVAE is 40960 PCM.

### ISSUE THREAD

**Issue by suzhiba** [neonbjb/tortoise-tts#570]
Hi，
In appendix B.1 VQVAE,  the description is "Input samples were constricted to 40960 PCM readings, or 2 seconds of audio". 2 seconds audio in 24k is 48000 , while 44100 sample in 22.05k.  Why is 40960 used here？It seems like that we have 2 different conditions.

**Comment by neonbjb** [comment]
I'm aligning by (multiples of) powers of 2 here, not by seconds or sample rate. This choice should not functionally change the network in any way.

In general for training CNNs it is important that the input dimensions are a multiple of the downsampling you want to perform, which is why sticking with powers of 2 makes things easier.
