### ISSUE TITLE
Gradio API broken

### ISSUE THREAD

**Issue by mueller91** [neonbjb/tortoise-tts#616]
Hi all,

the Gradio API / Huggingface API does not work: While it successfully returns a filepath, this filepath does not exist on the server.
Here is the code to reproduce:

```
    
from gradio_client import Client
def tts(txt, voice_id):
    client = Client("https://manmay-tortoise-tts.hf.space/")
    result = client.predict(txt, "/tmp/test.txt", voice_id, voice_id, "No", api_name="/predict")
    audio_url, _ = result
```

This returns
`{"detail":"File not found: /tmp/gradio/1c817c90297c81b90978b42d061cb13056e171e9/audio.wav."}`
when I query
`https://manmay-tortoise-tts.hf.space/file=/tmp/gradio/6ce6450aa5e96bf39560acd64d18f5e26f98dd18/audio.wav`.

**Comment by manmay-nakhashi** [comment]
@mueller91 let me check.

**Comment by fakerybakery** [comment]
Hi @mueller91 and @manmay-nakhashi.
The `audio_url` is not a URL, it is a temporary file on your computer.
The URL you are trying to query, `https://manmay-tortoise-tts.hf.space/file=/tmp/gradio/6ce6450aa5e96bf39560acd64d18f5e26f98dd18/audio.wav`, does not exist because the audio file is on your local computer. If you try opening the `/tmp/gradio/6ce6450aa5e96bf39560acd64d18f5e26f98dd18/audio.wav` file on your local computer, you should find the audio file there.
Could you try running your code again and running this Terminal command:
```
open /tmp/gradio/..... temporary generated string ..../audio.wav
```
Hope this helps!
