### ISSUE TITLE
Colab doesn't work

### ISSUE THREAD

**Issue by nwatab** [neonbjb/tortoise-tts#66]
Since 3acca1445adb0ed7869c53d5e26ef955ec7b87c2, Colab notebook doesn't work. To use old code, a user should replace the first cell with
```
# the scipy version packaged with colab is not tolerant of misformated WAV files.
# install the latest version.
!pip3 install -U scipy

!git clone https://github.com/neonbjb/tortoise-tts/
%cd tortoise-tts
!git checkout 7f9f1dbfc394d76757ba9c3fb22247b7cc0f52de
!pip3 install -r requirements.txt
!python3 setup.py install
```

**Comment by ChiefJoep** [comment]
Unfortunately it still doesn't work. Either with or without this change, the 2nd cell shows:

---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

[<ipython-input-9-0f6e1f002713>](https://localhost:8080/#) in <module>()
      7 import IPython
      8 
----> 9 from tortoise.api import TextToSpeech
     10 from tortoise.utils.audio import load_audio, load_voice, load_voices
     11 

1 frames

[/content/tortoise-tts/tortoise/models/cvvp.py](https://localhost:8080/#) in <module>()
      5 from torch.utils.checkpoint import checkpoint
      6 
----> 7 from models.arch_util import AttentionBlock
      8 from models.xtransformers import ContinuousTransformerWrapper, Encoder
      9 

ModuleNotFoundError: No module named 'models'


---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

I'm too unfamiliar with this to apply a fix or change myself, is this easy to circumvent?

**Comment by rayanarman** [comment]
in the folder tortoise-tts/tortoise/models/ there is a file called cvvp.py. In that file, change lines 7 and 8 to read as follows:

from tortoise.models.arch_util import AttentionBlock
from tortoise.models.xtransformers import ContinuousTransformerWrapper, Encoder

essentially just append "tortoise." before the models for both the lines.

hope that helps.

**Comment by neonbjb** [comment]
Hey, I just pushed a fix for this. I apologize for the inconvenience. Thanks for the digging @rayanarman

**Comment by nwatab** [comment]
Thank you for quick great job.
